[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "api"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  autoLaunch = false
